language: csharp
solution: TravisSample.sln
install:
  - nuget restore Demo-NUnit.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Demo-NUnit.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Demo-NUnit.Test/bin/Release/Demo-NUnit.Test.dll